--- #DO NOT REMOVE OR CHANGE THIS LINE! ALWAYS LEAVE SPACE AFTER COLONS!
dropdown1: "Retailer"
buval: "Retailer"
EmailDate: "Email Date"
SenderEmailAddress:  "Sender Email Address"
EmailSubjec: "Email Subject"
Filename: "Filename"
SN: "SN"
FID: "IA FID"
VID: "IA VID"
vName: "IA Vendor Name"
vTel: "IA Vendor Telephone"
fName: "IA Factory Name (in English)"
fNameC: IA Factory Name (in Chinese)
fLocE: "IA Factory Location (in English)"
fLocC: "IA Factory Location (in Chinese)"
fCon: "IA Factory Contact Person"
fTel: "IA Factory Telephone"
poStart: "IA PO #"
poReinspection: "Re-inspection"
typeofInspection: "IA Type of Inspection"
rDate: "IA Request Inspection Date"
aDate: "IA Request Date Accept"
multiFactory: "IA Multi Factory"
itemNo: "IA Item No"
quantity: "IA Quantity"
specialPro: "Special Program"
totalIA: "Total IA Count"
poCount: "Count PO"
