--- #DO NOT REMOVE OR CHANGE THIS LINE! ALWAYS LEAVE SPACE AFTER COLONS!
VID: "'VID' should be 4 digits! [ROW:3]"
FID: "'FID' should be numbers! [ROW:7]"
vName: "'Vendor Name' cannot be empty or longer than 255! [ROW:4]"
vTel: "'Vendor Telephone' cannot be empty or longer than 255! [ROW:5]"
fName: "'Factory Name (in English)' cannot be empty or longer than 255! [ROW:8]"
fNameC: "'Factory Name (in Chinese)' cannot be empty or longer than 255! [ROW:9]"
fLocE: "'Factory Location (in English)' cannot be empty or longer than 255! [ROW:10]"
fLocC: "'Factory Location (in Chinese)' cannot be empty or longer than 255! [ROW:11]"
fCon: "'Factory Contact' cannot be empty or longer than 255! [ROW:12]"
fTel: "'Factory Telephone' cannot be empty or longer than 255! [ROW:13]"
rDate: "'Request Inspection Date' must be a valid date (2019/01/01) and later than today [ROW:6]"
poStart: "'PO#' must be a positive number and not blank!"
poReinspection: "'Re-inspection' must be one of 'No', 'b/c missing' or 'b/c fail'!"
typeofInspection: "'Type of Inspection' must be either 'New' or 'Cancellation'!"
itemNo: "'Item No' must be a postive number and not blank!"
multiFactory: "'MultiFactory' must be either 'Yes' or 'No'!"
quantity: "'Quantity' must be a postive number!"
specialPro: "'Special Program' must be either blank or one of the valid programs!"
hasRow: "Must have at least one PO record!"
dropdown1: "'Retailer' must not be empty!"
buval: "'Retailer' must be one of the valid values!"