--- #DO NOT REMOVE OR CHANGE THIS LINE! ALWAYS LEAVE SPACE AFTER COLONS!
VID: "ID,\\\\fnp1423mp01.lowes.com\\Data1\\SHARE\\EVERYONE\\C-QA\\Operation Team\\Email Template\\Vendor.xlsx"
FID: "Factory ID,\\\\fnp1423mp01.lowes.com\\Data1\\SHARE\\EVERYONE\\C-QA\\Operation Team\\Email Template\\Factory.xlsx"